### ISSUE TITLE
Getting the position(rank) of a member/user 

### ISSUE THREAD

**Issue by DashCruft** [MrAugu/discord-xp#14]
Hey There! 👋
it would be awesome if you guys add a new method for getting someone's rank or leaderboard positron. I've made a RankCard and I can't be setting the position or the rank of them in the server.

If there is going to be a method, our work will be much eaiser. If there is other ways, Please include

**Comment by RadPlayzYT** [comment]
Hey DashCruft, Im Not One Of This Package Creators, But This Is Actually Possible But It  Required A Little Bit Of Coding, If Actually Make It I Will Sned it
sry for my bad english

**Comment by MrAugu** [comment]
Hello! That would require to query an entire server's leaderboard and then find the position for a member, I could add an experimental feature until I find an optimal way to query the database.

**Comment by MrAugu** [comment]
The `master` (future `1.1.7`) branch now accepts a new optional `fetchPosition`, option (`false` by default), if true, the user will be applied a new property called `position`. On large servers, the query is going to be slower, until a proper optimized implementation can be made.
