### ISSUE TITLE
'leaderboard.map is not a function' while trying to make a leaderboard

### ISSUE THREAD

**Issue by Lekrkoekj** [MrAugu/discord-xp#15]
I'm currently trying to make a leaderboard command. The one that was provided on the [npm website](https://www.npmjs.com/package/discord-xp#examples) didn't work for me, so I decided to try it myself. This is the code that I currently have:
![image](https://user-images.githubusercontent.com/50798931/99150193-15a33e80-2693-11eb-9455-a917e55642af.png)

And it returns this in the logs:
![image](https://user-images.githubusercontent.com/50798931/99150221-39668480-2693-11eb-9883-35990ccce571.png)

I don't know why this is happening or if I can fix it so any help is appreciated!

**Comment by MrAugu** [comment]
Check what `Levels.fetch` is returning, you probably do not have required intents.

**Comment by MrAugu** [comment]
The function `Levls.fetch` is an asynchronous function, meaning in order to use it like that you have to add the `await` keyword before querying the function.
