### ISSUE TITLE
Update MQuery

### ISSUE THREAD

**Issue by Spencer-0003** [MrAugu/discord-xp#17]
Could you update the version of MQuery required to use this? The current one is being labelled as vulnerable.
![image](https://user-images.githubusercontent.com/36741900/102668764-ad111b00-4184-11eb-9b2b-4cfd8ec844d7.png)

**Comment by MrAugu** [comment]
I updated the mongoose to `v5.11.11`, I will further update mongoose as soon as their issues with the mongodb driver are fixed.
