### ISSUE TITLE
lastUpdated in db

### ISSUE THREAD

**Issue by iantomareels** [MrAugu/discord-xp#29]
I tried pulling the latest time a user got updated but it doesn't seem to update. 
I am trying to set a delay on the xp gaining.

It stays the same time even though xp is getting added to the user.

I a trying to pull calculate it using the following code:
```
const user = await Levels.fetch(message.author.id, message.guild.id);
    if (Date.now() - user.lastUpdated > 60000) {
    console.log("added xp");
    const hasLeveledup = await Levels.appendXp(
      message.author.id,
      message.guild.id,
      randomXP
    );
```

**Comment by MrAugu** [comment]
Will be investugated.

**Comment by MrAugu** [comment]
Will be investigated.

**Comment by gruselhaus** [comment]
Yes, I noticed this as well.

**Comment by MrAugu** [comment]
The fix has been merged into master, and will be punished to NPM in the next release.
