### ISSUE TITLE
RangeError: Target level should be a positive number.

### ISSUE THREAD

**Issue by NamanPrakash** [MrAugu/discord-xp#33]
# RangeError: Target level should be positive number.
when I'm using
```javascript
Levels.xpFor(user.level);
```
It is giving error:
```
(node:4) UnhandledPromiseRejectionWarning: RangeError: Target level should be a positive number.
at Function.xpFor (/app/node_modules/discord-xp/index.js:303:32)
at Function.fetch (/app/node_modules/discord-xp/index.js:189:35)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async Client.module.exports (/app/command.js:16:18)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I don't know why it's happening.
can somebody help?
Im using version: `1.1.13`

**Comment by NamanPrakash** [comment]
pls do something @MrAugu

**Comment by gruselhaus** [comment]
What value do you pass into the function? What's the value of `user.level`?

**Comment by Myst82015** [comment]
Did you modify the database?

**Comment by MrAugu** [comment]
The issue has been fixed with the version `v.1.1.14` which you can get on npm today. See the instructions in the README.md for updating.

**Comment by NathanAlcantara** [comment]
I update and yet got the error, anyone can validade too please?

**Comment by NamanPrakash** [comment]
@gruselhaus `user.level` is the level of the user and mine is 0 for now

**Comment by NamanPrakash** [comment]
I have made a repository about it it NamanPrakash/Dobby

**Comment by NamanPrakash** [comment]
I have made a repository of this discord bot it is [NamanPrakash/Dobby](https://github.com/NamanPrakash/Dobby)

**Comment by NamanPrakash** [comment]
@Myst82015 I did not modify the database

**Comment by NamanPrakash** [comment]
thx for reopening @MrAugu

**Comment by MrAugu** [comment]
Seems like the library is not updated on your end. And the implementation is not correct, the `neededXp` should be `level + 1` anyways.
Run the commands below to update to `v1.1.14`:
```
npm uninstall discord-xp --force
```
```
npm i discord-xp@1.1.14
```

**Comment by NamanPrakash** [comment]
yes it is working now
thx

**Comment by MrAugu** [comment]
@NathanAlcantara Follow the instructions above too.

**Comment by NathanAlcantara** [comment]
@MrAugu Worked for me, arigathanks!!
