### ISSUE TITLE
Xp per rank

### ISSUE THREAD

**Issue by OverXone** [MrAugu/discord-xp#36]
Is there a way to set a determined XP for each rank to rank up, instead of default XP for level 1 50XP, cause I want to use the XP package for a points system.

**Comment by Myst82015** [comment]
> 
> 
> Is there a way to set a determined XP for each rank to rank up, instead of default XP for level 1 50XP, cause I want to use the XP package for a points system.

That 's not possible. Atleast not now.

**Comment by OverXone** [comment]
> > Is there a way to set a determined XP for each rank to rank up, instead of default XP for level 1 50XP, cause I want to use the XP package for a points system.
> 
> That 's not possible. Atleast not now.

Then, any suggestion for an XP system to set determined XP to ranks?

**Comment by Myst82015** [comment]
> 
> 
> > > Is there a way to set a determined XP for each rank to rank up, instead of default XP for level 1 50XP, cause I want to use the XP package for a points system.
> > 
> > 
> > That 's not possible. Atleast not now.
> 
> Then, any suggestion for an XP system to set determined XP to ranks?

?

**Comment by OverXone** [comment]
> ?
I want to set an XP system to rank up when reached the determined XP.

**Comment by Myst82015** [comment]
well as I said, `discord-xp` doesn't do that.
Code your own system then.
