### ISSUE TITLE
help with leaderboard

### ISSUE THREAD

**Issue by Pykera** [MrAugu/discord-xp#38]
Leaderboard it's not working and I don't know if that is a module problem :c
![image](https://user-images.githubusercontent.com/57367252/116024706-29c96f80-a625-11eb-9180-d531f4a4b4e9.png)

**Comment by Pykera** [comment]
![image](https://user-images.githubusercontent.com/57367252/116024760-45347a80-a625-11eb-9891-5ab8824b0667.png)
I forget to paste the code, sorry.

**Comment by Myst82015** [comment]
> 
> 
> Leaderboard it's not working and I don't know if that is a module problem :c
> ![image](https://user-images.githubusercontent.com/57367252/116024706-29c96f80-a625-11eb-9180-d531f4a4b4e9.png)

Can you send the whole error?
Also I suggest you join the officla Help server (discord.gg/rk7cVyk) and make a ticket there.

**Comment by MrAugu** [comment]
Issue resolved.
