### ISSUE TITLE
Way to view current and needed xp to level up

### ISSUE THREAD

**Issue by Misly16** [MrAugu/discord-xp#4]
Hello, I think it would be quite nice to add a way to view how much xp a user needs to level up!

**Comment by MrAugu** [comment]
I will be adding a function to calculate that.

**Comment by Gav-Vu** [comment]
I really need that.

**Comment by MrAugu** [comment]
@Gav-Vu @Misly16 I have added the `xpFor(targetLevel)` function allowing you to calculate the required xp, read the changelog.

**Comment by MrAugu** [comment]
Update the package to receive the changes.
