### ISSUE TITLE
Leaderboard duplicate entries

### ISSUE THREAD

**Issue by Zxoir** [MrAugu/discord-xp#44]
`const Levels = require('discord-xp');

module.exports = {
    name: 'leaderboard',
    aliases: ['ldrboard'],
    description: 'Displays the servers top 5 leveled users.',
    async execute(message, args, db, client) {
        const rawLeaderboard = await Levels.fetchLeaderboard(message.guild.id, 5);

        if (rawLeaderboard.length < 1) return reply("Nobody's in leaderboard yet.");

        const leaderboard = await Levels.computeLeaderboard(client, rawLeaderboard, true); // We process the leaderboard.

        const lb = leaderboard.map(e => `${e.position}. ${e.username}#${e.discriminator}\nLevel: ${e.level}\nXP: ${e.xp.toLocaleString()}`); // We map the outputs.

        message.channel.send(`**Leaderboard**:\n\n${lb.join("\n\n")}`);
    },
};`

Whenever I use this command I get duplicated values as such
https://prnt.sc/13h7t1q

**Comment by MrAugu** [comment]
The root cause, most likely, is faulty code that's creating new entries in the database when they shouldn't be, leading to duplicate results as seen in the photo. This has nothing to do with the `discord-xp` package itself but rather with the user's own misuse.
