### ISSUE TITLE
Failed to append xp

### ISSUE THREAD

**Issue by Aurioska25** [MrAugu/discord-xp#48]
Hello **everyone**. 

So I run in a **problem** where I can't locate where can be wrong, and this happens almost a month.. So maybe here I will manage to find, help or solution how can I fix this. 

IN console always getting this **error** : 
**Failed to append xp: ValidationError: level: Cast to Number failed for value "NaN" at path "level"**

**Comment by Myst82015** [comment]
This is clearly a You-problem. 
You migh've given xp of type string, null or undefined
-> that when module tried to operate got NaN which mongoose blocked from stored in the db

If you still need help, join our support server and make a ticket: https://discord.gg/rk7cVyk
