### ISSUE TITLE
When a user types a message, the bot creates duplicates of the user and guild in the db

### ISSUE THREAD

**Issue by NotTimIsReal** [MrAugu/discord-xp#51]
On the message the bot creates duplicates of that. If I manually delete the dbs it won't break only for new users.

**Comment by NotTimIsReal** [comment]
<img width="379" alt="Screen Shot 2021-07-22 at 8 17 26 pm" src="https://user-images.githubusercontent.com/84319818/126624290-aee8e699-b0b7-4d30-b518-5add38abf308.png">

**Comment by Myst82015** [comment]
So this normally doesn not happen, the package only creates a user if it doesn't exist when using appendXp().

I'll guess then it's a you problem and without any code there's nothing I can help with.

In addition this is for 'real' bugs and not for normal questions. Join our discord server https://discord.gg/aP9UYfaFa4 and make a ticket. If you do so provide your code.
