### ISSUE TITLE
0's on leaderboard not showing

### ISSUE THREAD

**Issue by idontgiveescheat** [MrAugu/discord-xp#52]
@MrAugu The package is replacing all the 0's on the leaderboard with a comma.
Example:
![image](https://user-images.githubusercontent.com/78556094/135361176-f073b01f-6de5-4903-ba6d-c25674d67c84.png)
If it's a code error (which I don't think it is because it was working perfectly fine before today), here's my code:
![image](https://user-images.githubusercontent.com/78556094/135361296-836a488e-b63d-46c0-9e5b-67a575b606f6.png)

**Comment by Myst82015** [comment]
hm, weird. I'll take a look on the weekend.

**Comment by Myst82015** [comment]
![grafik](https://user-images.githubusercontent.com/34489470/183305992-195c0aec-946b-4f55-9270-564deefb2c11.png)
I'm unable to reproduce that behavior
