### ISSUE TITLE
Cant delete user or guild

### ISSUE THREAD

**Issue by DemonixDev** [MrAugu/discord-xp#56]
in guildDelete event I try to delete guild with
`await <Levels>.deleteGuild(guild id here)` and it gives me time out error, latest discord-xp and mongoose 6.0.6

**Comment by Myst82015** [comment]
This is likely due to a poor connection on your end.

**Comment by DemonixDev** [comment]
No beacuse other mongoose stuff work. It happend to me before when i was doing
```
await <schema>.findOne({ filters }, async (err, data) => {
    Rest of code
});
```
Now im doing 
```
let data
data = await schema.findOne({ filters })
```
Or
```
<schema>.findOne({ filters }, async (err, data) => {
    Rest of code
});
```

**Comment by Myst82015** [comment]
why don't you await it anymore?

In addition: it works like a charm with     `"mongoose": "^6.0.12"`

Can you also provide the full error?

**Comment by DemonixDev** [comment]
I will try to update to mongoose 6.0.12 and see if it work, if it wont i will get back to you

**Comment by DemonixDev** [comment]
> why don't you await it anymore?

I await Levels.deleteUser and other discord-xp requests, i await it when doing second things i sent before. When third method when i await it gives that timeout error

**Comment by DemonixDev** [comment]
I tried using mongoose 6.1.4, still doesnt work

**Comment by Myst82015** [comment]
Issue was resolved via the Discord server.
