### ISSUE TITLE
Update mongoose to stable version 

### ISSUE THREAD

**Issue by GoAwayGod** [MrAugu/discord-xp#63]
Prototype pollution Schema.path in automattic/mongoose - https://github.com/advisories/GHSA-f825-f98c-gj3g
Depends on vulnerable versions of mongoose
mongoose  <6.4.6

**Comment by Myst82015** [comment]
That is correct. We'll look into it.
![grafik](https://user-images.githubusercontent.com/34489470/183574199-5176b049-4177-4594-b088-f64502d71548.png)

**Comment by Myst82015** [comment]
I fixed it in the role reward branch so far.


https://github.com/MrAugu/discord-xp/commit/0e923fb4f25dff4f2503add89d07d462a7833bcd

**Comment by Myst82015** [comment]
Fixed with #69
