### ISSUE TITLE
No matching version discord-xp@^1.1.17

### ISSUE THREAD

**Issue by JamesCicada** [MrAugu/discord-xp#65]
when trying to install version 1.1.17 it returns the error "No matching version found for discord-xp@^1.1.17."

**Comment by Myst82015** [comment]
The published version on npm is version 1.1.16.
Only the role reward branch is technically 1.1.17 but that isn't published on npm.
https://www.pluralsight.com/guides/install-npm-packages-from-gitgithub

`npm i https://github.com/MrAugu/discord-xp/tarball/role-rewards` should do the trick but this branch isn't published yet -> bugs may occur.
