### ISSUE TITLE
e.id is undefined.

### ISSUE THREAD

**Issue by okizekdev** [MrAugu/discord-xp#66]
Hello, i've created some leaderboard command, well, it was working for a moment, but now it's broken, 
![image](https://user-images.githubusercontent.com/90500948/194753741-b5c30ac7-0482-435f-b99d-04ad49104ee8.png)
any ideas?

My code below:

```const rawLB = await DiscordXp.fetchLeaderboard(interaction.guildId, 10);
        const LB = await DiscordXp.computeLeaderboard(client, rawLB, true);

        if (rawLB.length < 1) return interaction.reply({ content: "\`[ ❌ ]\` Na tym serwerze nikt nie ma poziomów!", ephemeral: true });

        const l = LB.map(e => `\`${e.position}.\` <@${e.id}>:\n  **Poziom: ${e.level}**\n  **XP: ${e.xp.toString()}**`);

        interaction.reply({ embeds: [{
            title: "Leaderboard serwera " + interaction.guild.name,
            description: `${l.join("\n\n")}`,
            color: "PURPLE"
        }] });```

**Comment by Myst82015** [comment]
Sorry for the late reply but I'm unable to reproduce the issue.
Since I haven't heard any similar problem so far, I'll close this issue. If it still persists (I highly doubt that when looking a the date) you can reopen it.
