### ISSUE TITLE
Bad typings

### ISSUE THREAD

**Issue by needhamgary** [MrAugu/discord-xp#67]
I installed the (typescript) package in my project with no issues. When I import it into my `messageCreate` event, all of my current mongoose schema imports  `type never | null` as of version 1.1.19. See attached images.
#
Before importing in event.
![image](https://user-images.githubusercontent.com/23411307/220696903-609d2758-9e18-4b8c-aa0c-a7d342e7550d.png)
##
After importing in event with `discord-xp-typescript`
![image](https://user-images.githubusercontent.com/23411307/220696769-a7e87bfb-ae52-4ad9-bbd1-4136e781f0b0.png)
#
As I install `discord-xp` into my project my imports auto change to `type any`.

Before installing package.
![image](https://user-images.githubusercontent.com/23411307/220696903-609d2758-9e18-4b8c-aa0c-a7d342e7550d.png)
##
After installing the package.
![image](https://user-images.githubusercontent.com/23411307/220698184-8da31b2f-d57f-4d45-9ce2-88ea13f8ade4.png)

I updated ALL of my existing node_modules to latest versions before creating this issue.
Node version is 16.19.0
Discord.js v14.7.1

**Comment by Myst82015** [comment]
The pull request was merged.
