### ISSUE TITLE
Update NPM Package.

### ISSUE THREAD

**Issue by Adler-D3R** [MrAugu/discord-xp#70]
Hey,

I noticed that the package version on GitHub and the package version on NPM doesn't match.
Is there any way you update the one on NPM ? It's not the latest version.
Thanks for understanding.

Kind regards.

**Comment by Myst82015** [comment]
This is correct. I'll look into it and talk to MrAugu to push the update to npm.

However you can also install the newest version  **directly** from github.

`npm i https://github.com/MrAugu/discord-xp` (if I recall that correctly)
