### ISSUE TITLE
This is weird in the schema

### ISSUE THREAD

**Issue by Strooss** [MrAugu/discord-xp#71]
![image](https://github.com/MrAugu/discord-xp/assets/102289594/4deae42e-4578-46d6-a288-8224b5fa1146)
![image](https://github.com/MrAugu/discord-xp/assets/102289594/f6effd5e-4992-4e77-86ed-55e77168fc68)
So you adding values to the schema that dont even exist in the schema

**Comment by Myst82015** [comment]
Hello there.
Please read the the code carefully. We are not setting ```user.cleanXp``` or ```user.cleanNextLevelXp```. 
We are returning the ```user``` object so these to are just additional properties for special use cases like a canvacord integration.

Hope, that helped. Feel free to ask if you face any problems ;)
