### ISSUE TITLE
Roles on levelling

### ISSUE THREAD

**Issue by tec-wizard** [MrAugu/discord-xp#8]
Can I add roles on leveling by checking certain levels for users ?
Also I need an invite to your server

**Comment by tec-wizard** [comment]
anyone ?

**Comment by Lioness100** [comment]
The `Levels.appendXp()` function, which you use to give members EXP, returns a `boolean`. If the `boolean` is true, the user has leveled up. Example in code:
```js
const hasLeveledUp = await Levels.appendXp(user, guild, amount);
if (hasLeveledUp) console.log(`${user.username} has leveled up);
```
---
Inside the `hasLeveledUp `if` block, you can do whatever you want, including assign roles. For example:
```js
if (hasLeveledUp) {
const user = await Levels.fetch(message.author, message.guild);
const levelRole = message.guild.roles.cache.find(role => role.name === `Level ${user.level}`);
message.guild.member(user).roles.add(levelRole);
};
```
This example finds the appropriate role by fetching the user's EXP data and gives them that role. Obviously, this is just a bare template, you can put in whatever fits your server.

**Comment by tec-wizard** [comment]
Ok thanks for the help.
